const demoProducts=[
{id:'samsung-a16',name:'Samsung Galaxy A16',cat:'Mobile',img:'📱',mrp:15999,offers:[{sellerId:'CB100001',seller:'Royal Mobile Store',price:14799,stock:12,rating:4.8,location:'Dubrajpur',status:'approved'},{sellerId:'CB100002',seller:'Digital Mobile World',price:14999,stock:8,rating:4.6,location:'Suri',status:'approved'},{sellerId:'CB100003',seller:'Online Affiliate Deal',price:14599,stock:99,rating:4.5,location:'Online',affiliate:'#',status:'approved'}]},
{id:'canon-toner',name:'Canon Copier Toner',cat:'Copier',img:'🖨️',mrp:2400,offers:[{sellerId:'CB100004',seller:'Tech CND Copier Solution',price:1950,stock:6,rating:4.9,location:'Birbhum',status:'approved'},{sellerId:'CB100005',seller:'Printer Parts Hub',price:2050,stock:9,rating:4.4,location:'Kolkata',status:'approved'}]},
{id:'sports-shoes',name:'Sports Shoes',cat:'Footwear',img:'👟',mrp:999,offers:[{sellerId:'CB100006',seller:'Mode Shoe',price:599,stock:20,rating:4.7,location:'Local Shop',status:'approved'},{sellerId:'CB100003',seller:'Online Affiliate Deal',price:549,stock:50,rating:4.3,location:'Online',affiliate:'#',status:'approved'}]}
];
const sellerNames={CB100001:'Royal Mobile Store',CB100002:'Digital Mobile World',CB100003:'Online Affiliate Deal',CB100004:'Tech CND Copier Solution',CB100005:'Printer Parts Hub',CB100006:'Mode Shoe'};
function getLS(k,d=[]){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}}
function setLS(k,v){localStorage.setItem(k,JSON.stringify(v))}
function getCart(){return getLS('cb_cart',[])}
function saveCart(c){setLS('cb_cart',c);updateCartCount()}
function getAllProducts(){
  let approved=getLS('cb_seller_products',[]).filter(x=>x.status==='approved');
  let products=JSON.parse(JSON.stringify(demoProducts));
  approved.forEach(sp=>{
    let id=sp.productId||('custom-'+sp.id);
    let p=products.find(x=>x.id===id);
    let offer={sellerId:sp.sellerId,seller:sp.sellerName,price:Number(sp.price||0),stock:Number(sp.stock||1),rating:4.5,location:sp.location||'Local',size:sp.size||'',coupon:sp.coupon||'',discount:sp.discount||'',status:'approved'};
    if(p){p.offers.push(offer)} else {products.unshift({id,name:sp.name,cat:sp.category||'Shopping',img:sp.imageData||'🛍️',mrp:Number(sp.mrp||sp.price||0),offers:[offer]})}
  });
  return products;
}
function updateCartCount(){let n=getCart().reduce((a,b)=>a+b.qty,0);document.querySelectorAll('.cartCount').forEach(e=>e.textContent=n)}
function findProductOffer(productId,sellerId){let p=getAllProducts().find(x=>x.id===productId);let o=p?.offers.find(x=>x.sellerId===sellerId);return {p,o}}
function addToCart(productId,sellerId){let {p,o}=findProductOffer(productId,sellerId);if(!p||!o){alert('Product not found');return}let c=getCart();let k=c.find(x=>x.productId===productId&&x.sellerId===sellerId);if(k)k.qty++;else c.push({productId,sellerId,name:p.name,seller:o.seller,price:o.price,qty:1});saveCart(c);alert('Cart added: '+p.name+' from '+o.seller)}
function buyNow(productId,sellerId){let {p,o}=findProductOffer(productId,sellerId);if(!p||!o){alert('Product not found');return}setLS('cb_cart',[{productId,sellerId,name:p.name,seller:o.seller,price:o.price,qty:1}]);location.href='cart.html'}
function createOrder(){let cart=getCart();if(!cart.length){alert('Cart empty');return}let order={id:'CBORD'+Date.now(),items:cart,name:val('name'),mobile:val('mobile'),pincode:val('pincode'),address:val('address'),payment:document.querySelector('input[name=payment]:checked')?.value||'COD',status:'Pending Admin Accept',sellerStatus:'Waiting',courier:'Not Selected',date:new Date().toLocaleString()};let orders=getLS('cb_orders',[]);orders.unshift(order);setLS('cb_orders',orders);localStorage.removeItem('cb_cart');alert('Order placed. Admin accept korle seller panel e show hobe. Order ID: '+order.id);location.href='cart.html'}
function val(id){return document.getElementById(id)?.value||''}
function currentSellerId(){return new URLSearchParams(location.search).get('id')||localStorage.getItem('cb_seller_id')||'CB100001'}
function previewSellerImage(input){let f=input.files&&input.files[0]; if(!f)return; let r=new FileReader(); r.onload=e=>{document.getElementById('photoPreview').innerHTML='<img src="'+e.target.result+'" style="max-width:100%;max-height:170px;border-radius:14px">'; document.getElementById('imageData').value=e.target.result}; r.readAsDataURL(f)}
function submitSellerProduct(){let sellerId=currentSellerId();let list=getLS('cb_pending_products',[]);let item={id:'SP'+Date.now(),sellerId,sellerName:sellerNames[sellerId]||('Seller '+sellerId),productId:val('productId'),name:val('pname'),category:val('category'),size:val('size'),mrp:val('mrp'),price:val('price'),discount:val('discount'),coupon:val('coupon'),stock:val('stock'),location:val('location'),imageData:val('imageData')||'🛍️',status:'pending',date:new Date().toLocaleString()};list.unshift(item);setLS('cb_pending_products',list);alert('Product admin approval er jonno submit holo');location.reload()}
function adminApproveProduct(id){let pend=getLS('cb_pending_products',[]);let item=pend.find(x=>x.id===id);if(!item)return;pend=pend.filter(x=>x.id!==id);item.status='approved';let live=getLS('cb_seller_products',[]);live.unshift(item);setLS('cb_pending_products',pend);setLS('cb_seller_products',live);loadAdmin();}
function adminRejectProduct(id){let pend=getLS('cb_pending_products',[]).filter(x=>x.id!==id);setLS('cb_pending_products',pend);loadAdmin();}
function adminAcceptOrder(id){let orders=getLS('cb_orders',[]);let o=orders.find(x=>x.id===id);if(o){o.status='Admin Accepted';o.sellerStatus='Pending Seller Accept'}setLS('cb_orders',orders);loadAdmin();}
function sellerAcceptOrder(id){let orders=getLS('cb_orders',[]);let o=orders.find(x=>x.id===id);if(o){o.status='Confirmed';o.sellerStatus='Seller Accepted';o.courier=val('courier_'+id)||'Self Courier'}setLS('cb_orders',orders);loadSellerDashboard();alert('Order confirmed. Customer order e Confirmed show hobe.')}
function sellerRejectOrder(id){let orders=getLS('cb_orders',[]);let o=orders.find(x=>x.id===id);if(o){o.status='Seller Rejected';o.sellerStatus='Rejected'}setLS('cb_orders',orders);loadSellerDashboard();}
function loadAdmin(){
 let os=getLS('cb_orders',[]), pend=getLS('cb_pending_products',[]), live=getLS('cb_seller_products',[]);
 if(document.getElementById('orders'))orders.innerHTML=os.map(o=>`<tr><td><b>${o.id}</b><br>${o.date}</td><td>${o.name}<br>${o.mobile}<br>${o.pincode}<br>${o.address}</td><td>${o.items.map(i=>i.name+'<br><span class="small">From: '+i.seller+' ('+i.sellerId+')</span>').join('<hr>')}</td><td>${o.payment}<br>${o.courier||''}</td><td><b>${o.status}</b><br>${o.sellerStatus||''}<br>${o.status==='Pending Admin Accept'?`<button class="btn green" onclick="adminAcceptOrder('${o.id}')">Admin Accept</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5">No order yet</td></tr>';
 if(document.getElementById('pendingProducts'))pendingProducts.innerHTML=pend.map(p=>`<tr><td>${p.imageData&&p.imageData.startsWith('data:')?'<img src="'+p.imageData+'" style="width:70px;height:70px;object-fit:cover;border-radius:10px">':p.imageData}</td><td><b>${p.name}</b><br>${p.category} • Size: ${p.size}<br>Seller: ${p.sellerName} (${p.sellerId})</td><td>MRP ₹${p.mrp}<br>Price ₹${p.price}<br>Discount ${p.discount}%<br>Coupon ${p.coupon}</td><td><button class="btn green" onclick="adminApproveProduct('${p.id}')">Approve</button> <button class="btn orange" onclick="adminRejectProduct('${p.id}')">Reject</button></td></tr>`).join('')||'<tr><td colspan="4">No pending product</td></tr>';
 if(document.getElementById('adminStats'))adminStats.innerHTML=`<div class="card"><h3>${pend.length}</h3><p>Pending Products</p></div><div class="card"><h3>${os.length}</h3><p>Total Orders</p></div><div class="card"><h3>${live.length}</h3><p>Approved Seller Products</p></div>`;
}
function loadSellerDashboard(){
 let sellerId=currentSellerId();localStorage.setItem('cb_seller_id',sellerId);let sellerName=sellerNames[sellerId]||('Seller '+sellerId); if(document.getElementById('sellerInfo'))sellerInfo.innerHTML=`<b>${sellerName}</b><br>Seller ID: ${sellerId}`;
 let pend=getLS('cb_pending_products',[]).filter(x=>x.sellerId===sellerId), live=getLS('cb_seller_products',[]).filter(x=>x.sellerId===sellerId);
 if(document.getElementById('sellerProducts'))sellerProducts.innerHTML=[...pend,...live].map(p=>`<tr><td>${p.imageData&&p.imageData.startsWith('data:')?'<img src="'+p.imageData+'" style="width:60px;height:60px;object-fit:cover;border-radius:10px">':p.imageData}</td><td>${p.name}<br><span class="small">${p.category} • Size ${p.size}</span></td><td>₹${p.price}<br>Coupon ${p.coupon}</td><td><span class="badge">${p.status}</span></td></tr>`).join('')||'<tr><td colspan="4">No product submitted</td></tr>';
 let orders=getLS('cb_orders',[]).filter(o=>o.items.some(i=>i.sellerId===sellerId)&&['Admin Accepted','Confirmed','Seller Rejected'].includes(o.status));
 if(document.getElementById('sellerOrders'))sellerOrders.innerHTML=orders.map(o=>`<tr><td><b>${o.id}</b><br>${o.date}</td><td>${o.name}<br>${o.mobile}<br>${o.pincode}<br>${o.address}</td><td>${o.items.filter(i=>i.sellerId===sellerId).map(i=>i.name+' × '+i.qty+' ₹'+i.price).join('<br>')}</td><td><b>${o.status}</b><br>${o.courier||''}<br>${o.status==='Admin Accepted'?`<select id="courier_${o.id}"><option>Self Courier</option><option>ConnectBazar Courier</option><option>Ecomar Courier</option></select><br><button class="btn green" onclick="sellerAcceptOrder('${o.id}')">Seller Accept</button> <button class="btn orange" onclick="sellerRejectOrder('${o.id}')">Reject</button>`:''}</td></tr>`).join('')||'<tr><td colspan="4">Admin accept korar por order ekhane show hobe</td></tr>';
}
function loadCustomerOrders(){let os=getLS('cb_orders',[]);let el=document.getElementById('customerOrders');if(!el)return;el.innerHTML=os.map(o=>`<div class="seller"><div><b>${o.id}</b><br>${o.items.map(i=>i.name+' from '+i.seller).join('<br>')}<br><span class="small">${o.date}</span></div><div><span class="badge">${o.status}</span><br><span class="small">Courier: ${o.courier}</span></div></div>`).join('')||'<p>No order yet.</p>'}
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();loadCustomerOrders();});

function deliverySetStatus(id,status){let orders=getLS('cb_orders',[]);let o=orders.find(x=>x.id===id);if(o){o.deliveryStatus=status;o.status=status==='Delivered'?'Delivered':(status==='Picked Up'?'Picked Up by Courier':'Out for Delivery');}setLS('cb_orders',orders);loadDeliveryDashboard();}
function loadDeliveryDashboard(){let orders=getLS('cb_orders',[]).filter(o=>(o.courier||'').toLowerCase().includes('connectbazar'));let el=document.getElementById('deliveryOrders');if(!el)return;let assigned=orders.length,picked=orders.filter(o=>o.deliveryStatus==='Picked Up').length,del=orders.filter(o=>o.deliveryStatus==='Delivered').length;if(document.getElementById('deliveryStats'))deliveryStats.innerHTML=`<div class="stat-card"><h3>${assigned}</h3><p>Assigned</p></div><div class="stat-card"><h3>${picked}</h3><p>Picked Up</p></div><div class="stat-card"><h3>${del}</h3><p>Delivered</p></div>`;el.innerHTML=orders.map(o=>`<tr><td><b>${o.id}</b><br>${o.date}</td><td>${o.name}<br>${o.mobile}<br>${o.pincode}<br>${o.address}</td><td>${o.items.map(i=>i.name+'<br><span class="small">Seller: '+i.seller+'</span>').join('<hr>')}</td><td><b>${o.status}</b><br>Courier: ${o.courier}<br>${o.deliveryStatus||'Assigned'}</td><td><button class="btn green" onclick="deliverySetStatus('${o.id}','Picked Up')">Pickup Done</button> <button class="btn" onclick="deliverySetStatus('${o.id}','Out for Delivery')">Out for Delivery</button> <button class="btn orange" onclick="deliverySetStatus('${o.id}','Delivered')">Delivered</button></td></tr>`).join('')||'<tr><td colspan="5">ConnectBazar Courier order নেই</td></tr>';}
